version: "3.9"

services:
  db:
    image: mysql:8.4.3        # Bisa ganti ke 8.4.x jika tersedia
    container_name: 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
  app:
    #image: python:3.12
    build: .
    container_name: streamlit_app
    working_dir: /app
    volumes:
      - ./:/app
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501 --server.runOnSave=true
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      MYSQL_HOST: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: 

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  db_data:
